name: Trigger Sync to IDP Repo

on:
  push:
    branches:
      - main

jobs:
  trigger-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository_dispatch in IDP repo
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ github.token }}" \
            --data '{"event_type": "sync-code"}' \
            https://api.github.com/repos/alialh-cd-test-org/idp-repo/dispatches
